version: '3'
services:
  chocshop:
    build: .
    ports:
      - "8000:5000"
    env_file: .env
    links:
      - mysql:dbserver
    restart: always
  mysql:
    image: "mysql/mysql-server:latest"
    env_file: .env-mysql
    restart: always