version: '3'
services:
  chocshop:
    build: .
    ports:
      - "8000:5000"
    env_file: .env
    links:
      - mysql:dbserver
    restart: always
  mysql:
    environment:
      PUID: 1000
      PGID: 1000
    image: "mysql/mysql-server:latest"
    env_file: .env-mysql
    volumes: 
     - /home/chocshop/docker/mysql:/var/lib/mysql
    restart: always