"""back to decima

Revision ID: 01762007b980
Revises: 82721f470fb2
Create Date: 2020-04-20 13:19:20.559638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01762007b980'
down_revision = '82721f470fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
