"""extended user login

Revision ID: 74eb651b060a
Revises: b9a30d32a094
Create Date: 2020-04-06 09:27:16.049030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74eb651b060a'
down_revision = 'b9a30d32a094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
