"""empty message

Revision ID: c3090e6a4cf9
Revises: a9751b8050ef
Create Date: 2020-04-07 14:08:56.092132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3090e6a4cf9'
down_revision = 'a9751b8050ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('url', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'url')
    # ### end Alembic commands ###
