"""added user barcode

Revision ID: fbc1c07d8e03
Revises: c3090e6a4cf9
Create Date: 2020-04-17 10:21:54.044746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc1c07d8e03'
down_revision = 'c3090e6a4cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('barcode', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_barcode'), 'users', ['barcode'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_barcode'), table_name='users')
    op.drop_column('users', 'barcode')
    # ### end Alembic commands ###
